//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/PlayerInputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputController"",
    ""maps"": [
        {
            ""name"": ""MordernController"",
            ""id"": ""4258e905-f57e-4340-b524-78df222b6d2f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6cfa447b-d1c7-4c80-9693-9149bb954d3e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""4ffd1e7f-2d37-4f83-84be-b2de36a0e550"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Handwatch"",
                    ""type"": ""Button"",
                    ""id"": ""85d1e6c6-36c9-4efc-b0e7-382a6b1006f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""2033b222-5243-4284-97f1-1e944e2a0e62"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c5ff6565-1005-4440-81e8-b0b9805749b8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b23f8dec-e190-4efd-aabb-06cb6acae1b9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""449586bc-e7aa-431c-b7c3-ca0fa14ac760"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c9da1f69-dd05-4d26-89eb-1f690bb2b775"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""47fd36d5-44c0-4611-a9b2-1a411f4b7643"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""dbdbf03b-c5c0-459f-8a77-ee56aa5b9000"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dc852885-b543-4f41-8d27-faab51acea1f"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""573a548a-7152-45b0-931e-305488737f9e"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""012aa8c8-44c9-472e-8702-e28d93496079"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c2e8c726-469d-49e4-924d-d1f850b2d50f"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1502a594-f2b9-4c39-bf74-fe7cbc4cf61e"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02b1fcd6-a8dd-4b4b-941f-a38dac2673fb"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Handwatch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42a2c4b0-66f3-42f5-bd42-65dc050ad45c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Handwatch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MordernController
        m_MordernController = asset.FindActionMap("MordernController", throwIfNotFound: true);
        m_MordernController_Move = m_MordernController.FindAction("Move", throwIfNotFound: true);
        m_MordernController_Run = m_MordernController.FindAction("Run", throwIfNotFound: true);
        m_MordernController_Handwatch = m_MordernController.FindAction("Handwatch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MordernController
    private readonly InputActionMap m_MordernController;
    private IMordernControllerActions m_MordernControllerActionsCallbackInterface;
    private readonly InputAction m_MordernController_Move;
    private readonly InputAction m_MordernController_Run;
    private readonly InputAction m_MordernController_Handwatch;
    public struct MordernControllerActions
    {
        private @PlayerInputController m_Wrapper;
        public MordernControllerActions(@PlayerInputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_MordernController_Move;
        public InputAction @Run => m_Wrapper.m_MordernController_Run;
        public InputAction @Handwatch => m_Wrapper.m_MordernController_Handwatch;
        public InputActionMap Get() { return m_Wrapper.m_MordernController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MordernControllerActions set) { return set.Get(); }
        public void SetCallbacks(IMordernControllerActions instance)
        {
            if (m_Wrapper.m_MordernControllerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_MordernControllerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_MordernControllerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_MordernControllerActionsCallbackInterface.OnMove;
                @Run.started -= m_Wrapper.m_MordernControllerActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_MordernControllerActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_MordernControllerActionsCallbackInterface.OnRun;
                @Handwatch.started -= m_Wrapper.m_MordernControllerActionsCallbackInterface.OnHandwatch;
                @Handwatch.performed -= m_Wrapper.m_MordernControllerActionsCallbackInterface.OnHandwatch;
                @Handwatch.canceled -= m_Wrapper.m_MordernControllerActionsCallbackInterface.OnHandwatch;
            }
            m_Wrapper.m_MordernControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Handwatch.started += instance.OnHandwatch;
                @Handwatch.performed += instance.OnHandwatch;
                @Handwatch.canceled += instance.OnHandwatch;
            }
        }
    }
    public MordernControllerActions @MordernController => new MordernControllerActions(this);
    public interface IMordernControllerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnHandwatch(InputAction.CallbackContext context);
    }
}
